FROM public.ecr.aws/docker/library/node:24.14.1-alpine3.22 AS build
ARG VITE_OIDC_ISSUER
ARG VITE_OIDC_CLIENT_ID=tuba-web
ENV VITE_OIDC_ISSUER=${VITE_OIDC_ISSUER} \
    VITE_OIDC_CLIENT_ID=${VITE_OIDC_CLIENT_ID}
WORKDIR /src
RUN corepack enable
COPY web/package.json web/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY web/ ./
RUN pnpm build

FROM public.ecr.aws/nginx/nginx:1.29.1-alpine3.22
COPY deploy/docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /src/dist /usr/share/nginx/html
EXPOSE 8080
USER 65532:65532
