-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text UNIQUE NOT NULL CHECK (slug ~ '^[A-Za-z0-9_-]{1,64}$'), name text NOT NULL, namespace text UNIQUE NOT NULL CHECK (namespace ~ '^[A-Za-z0-9_-]{1,64}$'), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE identities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), issuer text NOT NULL, subject text NOT NULL, email text, display_name text, disabled_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(issuer,subject));
CREATE TABLE roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE, name text NOT NULL, permissions text[] NOT NULL DEFAULT '{}', system boolean NOT NULL DEFAULT false, UNIQUE(organization_id,name));
CREATE TABLE memberships (organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, identity_id uuid NOT NULL REFERENCES identities(id) ON DELETE CASCADE, role_id uuid NOT NULL REFERENCES roles(id) ON DELETE RESTRICT, created_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz, PRIMARY KEY(organization_id,identity_id,role_id));
CREATE TABLE cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT, title text NOT NULL CHECK(length(title) BETWEEN 1 AND 300), description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','in_progress','closed')), severity text NOT NULL CHECK(severity IN ('low','medium','high','critical')), assignee_identity_id uuid REFERENCES identities(id), version bigint NOT NULL DEFAULT 1, created_by uuid NOT NULL REFERENCES identities(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz);
CREATE INDEX cases_tenant_page_idx ON cases(organization_id, updated_at DESC, id DESC);
CREATE TABLE case_anomalies (case_id uuid NOT NULL REFERENCES cases(id) ON DELETE CASCADE, anomaly_id text NOT NULL, PRIMARY KEY(case_id,anomaly_id));
CREATE TABLE audit_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, organization_id uuid REFERENCES organizations(id), actor_identity_id uuid REFERENCES identities(id), action text NOT NULL, resource_type text NOT NULL, resource_id text NOT NULL, request_id text NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now(), before_state jsonb, after_state jsonb, metadata jsonb NOT NULL DEFAULT '{}');
CREATE INDEX audit_tenant_time_idx ON audit_events(organization_id, occurred_at DESC, id DESC);
CREATE TABLE idempotency_records (organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, identity_id uuid NOT NULL REFERENCES identities(id) ON DELETE CASCADE, operation text NOT NULL, idempotency_key text NOT NULL CHECK(length(idempotency_key) BETWEEN 8 AND 128), request_hash bytea NOT NULL, response_status integer NOT NULL, response_body jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, PRIMARY KEY(organization_id,identity_id,operation,idempotency_key));
CREATE INDEX idempotency_expiry_idx ON idempotency_records(expires_at);
-- +goose Down
DROP TABLE IF EXISTS idempotency_records,audit_events,case_anomalies,cases,memberships,roles,identities,organizations CASCADE;
