{{- if .Values.gateway.enabled }}
{{- if .Values.gateway.create }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ default .Release.Namespace .Values.gateway.namespace }}
  labels:
    {{- include "tuba.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: https
      hostname: {{ .Values.gateway.hostname | quote }}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.tlsSecretName }}
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "tuba.fullname" . }}-routes
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tuba.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ default .Release.Namespace .Values.gateway.namespace }}
      sectionName: {{ .Values.gateway.sectionName }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: {{ include "tuba.fullname" . }}-api
          port: {{ (index .Values.services "api").service.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "tuba.fullname" . }}-web
          port: {{ (index .Values.services "web").service.port }}
{{- end }}
