#!/usr/bin/env python3
"""Render a per-host Winlogbeat config from the repo template.

Only the TUBA_* placeholders are substituted. ${path.data} is left alone: Beats
resolves it from the --path.data argument at startup, so substituting it here
would pin the data directory into the file and break the per-instance isolation.

Secrets are read from .env.local (gitignored) rather than the command line.
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TEMPLATE = REPO / "deploy" / "components" / "windows-security-winlogbeat.example.yml"
OUT_DIR = REPO / ".runtime" / "win-log"

KAFKA_BROKERS = "10.6.68.248:29292"
# Bounds the first read so a freshly added source cannot dump its whole log
# history onto the single node before capacity is re-measured (A03).
INITIAL_CATCHUP = "24h"

# The source context id shares the source instance's hex suffix by construction.
CONTEXT_FOR = {
    "139": "ctx_a6b2f9d8a890cf30255a27103c90af47",
    "169": "ctx_03329669e117108230ae960fefef700a",
}


def load_env():
    values = {}
    for line in (REPO / ".env.local").read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.strip().startswith("#"):
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
    return values


def render(host, env):
    text = TEMPLATE.read_text(encoding="utf-8")
    # ${NAME:default} -> default, then ${NAME} -> value, for TUBA_* only.
    text = re.sub(r"\$\{(TUBA_[A-Z0-9_]+):([^}]*)\}", r"\2", text)
    substitutions = {
        "TUBA_SOURCE_CONTEXT_ID": CONTEXT_FOR[host],
        "TUBA_KAFKA_BROKERS": KAFKA_BROKERS,
        "TUBA_KAFKA_USERNAME": env["TUBA_WIN_%s_SCRAM_USER" % host],
        "TUBA_KAFKA_PASSWORD": env["TUBA_WIN_%s_SCRAM_PASSWORD" % host],
    }
    for name, value in substitutions.items():
        text = text.replace("${%s}" % name, value)
    if re.search(r"\$\{TUBA_[A-Z0-9_]+(:[^}]*)?\}", text):
        raise SystemExit("unsubstituted TUBA_ placeholder remains")
    # Header the deployment relies on when reading the file back later.
    header = (
        "# Generated by scripts/render_windows_winlogbeat_config.py from\n"
        "# deploy/components/windows-security-winlogbeat.example.yml\n"
        "# Host %s, source context %s, Kafka %s\n"
        "# First read is bounded to %s; remove ignore_older for steady state.\n"
        % (host, CONTEXT_FOR[host], KAFKA_BROKERS, INITIAL_CATCHUP)
    )
    return header + text


def main():
    hosts = sys.argv[1:] or ["139", "169"]
    env = load_env()
    for host in hosts:
        rendered = render(host, env)
        target = OUT_DIR / ("winlogbeat-%s.yml" % host)
        target.write_text(rendered, encoding="utf-8")
        masked = "\n".join(
            re.sub(r"^(  password: ).*$", r"\1<masked>", line)
            for line in rendered.splitlines()
        )
        print("=== %s -> %s (%d bytes) ===" % (host, target, len(rendered)))
        for line in masked.splitlines():
            if any(k in line for k in ("topic:", "username:", "password:", "hosts:", "dataset:", "name: Security", "ignore_older")):
                print("  " + line.strip())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
