import { useRef, useState, type ReactNode } from 'react';
import { Alert, App, Button, Descriptions, Drawer, Form, Input, InputNumber, Modal, Popconfirm, Select, Space, Steps, Table, Tabs, Tag } from 'antd';
import { useInfiniteQuery, useMutation, useQueries, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { z } from 'zod';
import { api, APIError, exportJobSchema, catalogSchema, collectorsSchema, entityPageSchema, getEntityBaseline, getEntityRisk, feedbackEvaluationSchema, feedbackMetricsSchema, queryString, releaseSchema, releasesSchema, releaseAuditSchema, sourceSchema, sourcesSchema, type CollectorSummary, type SourceInstance } from './api';
import { componentConfiguration, parseManagedConfiguration, IdempotencyDraft } from './workbench-requests';
import { useAuth } from './auth';
import { EmptyState, ErrorState, LoadingBlock, PageHeader, TimeValue } from './components';

const messageOf=(e:unknown)=>e instanceof Error?e.message:'请求失败，请重试。';
export function Panel({title,children,actions}:{title:string;children:ReactNode;actions?:ReactNode}){return <section className="panel"><header className="panel-head"><h2>{title}</h2>{actions}</header><div className="wb-panel-body">{children}</div></section>;}
export function Capability({title,description}:{title:string;description:string}){return <Alert type="info" showIcon title={title} description={description}/>;}
export function QueryState({query,children}:{query:{isLoading:boolean;error:unknown;refetch:()=>unknown};children:ReactNode}){return query.isLoading?<LoadingBlock/>:query.error?<ErrorState message={messageOf(query.error)} retry={()=>void query.refetch()}/>:<>{children}</>;}
function Json({value}:{value:unknown}){return <pre className="wb-json">{JSON.stringify(value,null,2)}</pre>;}
export function UnavailableAction({children,reason}:{children:ReactNode;reason:string}){return <Button disabled title={reason}>{children}</Button>;}

export function Catalog(){
 const {token}=useAuth();const [selected,setSelected]=useState<string>();
 const q=useQuery({queryKey:['catalog'],queryFn:({signal})=>api('/catalog',token,undefined,catalogSchema,signal)});
 const item=q.data?.datasets.find(x=>x.name===selected);
 return <div className="page-stack"><PageHeader eyebrow="DATA CATALOG" title="数据模型目录" description="可用字段、质量能力、授权级别和实际查询范围。"/>
 <QueryState query={q}><Panel title="数据模型" actions={<Tag>生产代次 {q.data?.active_generation??'—'}</Tag>}><Table rowKey="name" dataSource={q.data?.datasets} pagination={false} columns={[
 {title:'数据集',dataIndex:'name',render:(v:string)=><Button type="link" onClick={()=>setSelected(v)}>{v}</Button>},
 {title:'类型',dataIndex:'kind'},{title:'字段数',render:(_,r)=>r.fields.length},{title:'质量能力',dataIndex:'quality_statuses',render:(v:string[])=>v.join(' / ')},
 {title:'查询范围',render:()=>`最多 ${q.data?.max_time_range_day} 日`},{title:'',render:(_,r)=><Link to={`/events?dataset=${encodeURIComponent(r.name)}`}>检索事件 →</Link>} ]}/></Panel></QueryState>
 <Drawer title={`${selected??''} · 字段目录`} open={!!item} onClose={()=>setSelected(undefined)} size={700}>{item&&<><Alert type="info" title="原文和敏感字段分别授权" description="字段可用性以服务端 Catalog 和每次请求的权限检查为准。"/><Table rowKey="name" dataSource={item.fields} pagination={false} columns={[{title:'字段',dataIndex:'name'},{title:'类型',dataIndex:'type'},{title:'级别',dataIndex:'sensitivity'},{title:'检索',dataIndex:'searchable',render:(v:boolean)=>v?'✓':'—'},{title:'聚合',dataIndex:'aggregable',render:(v:boolean)=>v?'✓':'—'}]}/></>}</Drawer></div>;
}

export function Risks(){
 const {token}=useAuth();const [search,setSearch]=useState('');const [term,setTerm]=useState('');
 const q=useInfiniteQuery({queryKey:['risk-entities',term],initialPageParam:'',queryFn:({pageParam,signal})=>api(`/entities${queryString({query:term,cursor:pageParam,limit:20})}`,token,undefined,entityPageSchema,signal),getNextPageParam:p=>p.next_cursor||undefined});
 const entities=q.data?.pages.at(-1)?.items??[];
 const risks=useQueries({queries:entities.map(x=>({queryKey:['entities',x.entity_id,'risk'],queryFn:({signal}:{signal:AbortSignal})=>getEntityRisk(token,x.entity_id,signal)}))});
 const rows=entities.map((x,i)=>({...x,risk:risks[i]?.data,loading:risks[i]?.isLoading,error:risks[i]?.error}));
 return <div className="page-stack"><PageHeader eyebrow="ENTITY RISK" title="实体风险" description="查看可解释的风险贡献与修订；排序仅覆盖当前实体页。"/>
 <Panel title="风险调查" actions={<Input.Search aria-label="搜索风险实体" placeholder="实体标识" value={search} onChange={e=>setSearch(e.target.value)} onSearch={()=>setTerm(search.trim())}/> }>
 <QueryState query={q}><Table rowKey="entity_id" dataSource={rows} pagination={false} columns={[
 {title:'实体',dataIndex:'canonical_key',render:(v:string,r)=><Link to={`/entities/${encodeURIComponent(r.entity_id)}`}>{v}</Link>},{title:'类型',dataIndex:'entity_type'},
 {title:'风险',sorter:(a,b)=>Number(a.risk?.projection?.risk_score??-1)-Number(b.risk?.projection?.risk_score??-1),defaultSortOrder:'descend',render:(_,r)=>r.loading?'加载中':r.error?<Tag color="error">读取失败</Tag>:r.risk?.projection?.risk_score===undefined?'尚无风险贡献':<strong className="wb-risk">{Number(r.risk.projection.risk_score).toFixed(1)}</strong>},
 {title:'归因身份',dataIndex:'identity_strength'},{title:'修订',render:(_,r)=>r.risk?.revision??'—'},{title:'',render:(_,r)=><Link to={`/entities/${encodeURIComponent(r.entity_id)}?tab=risk`}>风险解释 →</Link>}
 ]}/>{q.hasNextPage&&<Button onClick={()=>void q.fetchNextPage()} loading={q.isFetchingNextPage}>下一页实体</Button>}</QueryState></Panel>
 <Capability title="风险范围" description="当前通过实体风险接口读取本页结果；全租户风险排行接口尚未上线。未产生投影不等于零风险。"/></div>;
}

export function Baseline(){
 const {token}=useAuth();const [search,setSearch]=useState('');const [term,setTerm]=useState('');const [entity,setEntity]=useState<string>();
 const entities=useInfiniteQuery({queryKey:['baseline-entities',term],initialPageParam:'',queryFn:({pageParam,signal})=>api(`/entities${queryString({query:term,cursor:pageParam,limit:50})}`,token,undefined,entityPageSchema,signal),getNextPageParam:p=>p.next_cursor||undefined});
 const q=useQuery({queryKey:['entities',entity,'baseline'],enabled:!!entity,queryFn:({signal})=>getEntityBaseline(token,entity!,signal)});
 const [selected,setSelected]=useState<unknown>();
 return <div className="page-stack"><PageHeader eyebrow="BASELINE MODELS" title="统计基线" description="按实体查看不可变模型、样本范围与冷启动状态。" actions={<UnavailableAction reason="训练任务写接口尚未上线">训练基线</UnavailableAction>}/>
 <Panel title="选择训练主体"><Input.Search value={search} onChange={e=>setSearch(e.target.value)} onSearch={()=>setTerm(search.trim())} placeholder="搜索账户或设备" aria-label="搜索基线实体"/>
 <QueryState query={entities}><Select className="wb-entity-select" aria-label="选择实体" showSearch optionFilterProp="label" placeholder="选择实体后查看模型" value={entity} onChange={setEntity} options={entities.data?.pages.flatMap(p=>p.items).map(x=>({value:x.entity_id,label:x.canonical_key+' / '+x.authority}))}/>{entities.hasNextPage&&<Button onClick={()=>void entities.fetchNextPage()} loading={entities.isFetchingNextPage}>更多实体</Button>}</QueryState></Panel>
 {!entity?<EmptyState title="请选择实体" description="模型覆盖范围按实体和生产代次查询，不使用示例评分。"/>:<QueryState query={q}><Panel title="模型版本"><Table rowKey={r=>`${r.model_id}:${r.model_version}`} dataSource={q.data?.items} locale={{emptyText:'尚未发布覆盖此实体的基线模型'}} pagination={false} columns={[
 {title:'模型',dataIndex:'model_id'},{title:'版本',dataIndex:'model_version'},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color={v==='ready'?'success':'warning'}>{v}</Tag>},{title:'完整日 / 样本',render:(_,r)=>`${r.complete_days} 日 / ${r.sample_count}`},
 {title:'训练截止',dataIndex:'training_cutoff',render:(v:string)=><TimeValue value={v}/>},{title:'代次',dataIndex:'generation'},{title:'',render:(_,r)=><Button type="link" onClick={()=>setSelected(r)}>详情</Button>}
 ]}/></Panel></QueryState>}
 <Capability title="冷启动与训练" description="样本不足时保持 cold_start；反馈不会在线修改模型。训练、发布评审与退役入口需要任务和模型管理接口支持。"/>
 <Drawer open={!!selected} title="模型与训练快照" onClose={()=>setSelected(undefined)} size={650}><Json value={selected}/></Drawer></div>;
}

export function Analysis(){
 const {token}=useAuth();const [kind,setKind]=useState('all');const [search,setSearch]=useState('');const [selected,setSelected]=useState<unknown>();
 const q=useQuery({queryKey:['releases'],queryFn:({signal})=>api('/releases',token,undefined,releasesSchema,signal)});
 const rows=q.data?.items.flatMap(r=>r.manifest.assets.map(a=>({...a,release:r.id,state:r.state,key:r.id+':'+a.asset_id}))).filter(a=>(kind==='all'||(kind==='features'?/feature/i.test(a.kind+' '+a.asset_id):/analysis|detect|rule/i.test(a.kind+' '+a.asset_id)))&&(a.asset_id+' '+a.release).toLowerCase().includes(search.toLowerCase()))??[];
 return <div className="page-stack"><PageHeader eyebrow="ANALYTICS" title="分析资产" description="从真实发布清单查看检测、特征和版本依赖。" actions={<UnavailableAction reason="资产内容编辑接口尚未上线">注册分析资产</UnavailableAction>}/>
 <Tabs activeKey={kind} onChange={setKind} items={[{key:'all',label:'资产清单'},{key:'rules',label:'检测与分析'},{key:'features',label:'特征资产'}]}/>
 <Panel title="资产与依赖" actions={<Input.Search aria-label="搜索分析资产" placeholder="资产 ID / 发布包" value={search} onChange={e=>setSearch(e.target.value)} allowClear/>}><QueryState query={q}><Table rowKey="key" dataSource={rows} pagination={{pageSize:10,showSizeChanger:true}} columns={[
 {title:'资产',dataIndex:'asset_id',render:(v:string,r)=><Button type="link" onClick={()=>setSelected(r)}>{v}</Button>},{title:'类型',dataIndex:'kind'},{title:'版本',dataIndex:'version'},
 {title:'发布包',dataIndex:'release',render:(v:string)=><Link to={`/releases/${encodeURIComponent(v)}`}>{v}</Link>},{title:'状态',dataIndex:'state'},{title:'精确依赖',dataIndex:'dependencies',render:(v:string[])=>v.join(' / ')||'无'}
 ]}/></QueryState></Panel><Capability title="资产编辑" description="当前可读取发布清单和依赖。规则阈值编辑、独立特征注册及评估任务创建尚缺少管理接口，不能从 manifest 推断规则参数。"/>
 <Drawer title="资产版本与血缘" open={!!selected} onClose={()=>setSelected(undefined)} size={650}><Json value={selected}/></Drawer></div>;
}

export function Feedback(){
 const {token}=useAuth();const [rule,setRule]=useState('');const [type,setType]=useState('');const [selected,setSelected]=useState<unknown>();
 const q=useQuery({queryKey:['feedback-evaluation',rule,type],queryFn:({signal})=>api(`/analysis/feedback/evaluation${queryString({rule_id:rule,feedback_type:type,limit:100})}`,token,undefined,feedbackEvaluationSchema,signal)});
 const metrics=useQuery({queryKey:['feedback-metrics'],queryFn:({signal})=>api('/analysis/feedback/metrics',token,undefined,feedbackMetricsSchema,signal)});
 return <div className="page-stack"><PageHeader eyebrow="OFFLINE EVALUATION" title="反馈与评估" description="人工反馈与证据上下文进入离线评估，保留规则和实体关联。" actions={<UnavailableAction reason="离线评估任务创建接口尚未上线">创建评估任务</UnavailableAction>}/>
 <Panel title="规则反馈质量"><QueryState query={metrics}><Table rowKey="rule_id" dataSource={metrics.data?.rules} pagination={false} columns={[{title:'规则',dataIndex:'rule_id'},{title:'真实异常',dataIndex:'true_positive'},{title:'误报',dataIndex:'false_positive'},{title:'漏报',dataIndex:'false_negative'},{title:'证据不足',dataIndex:'inconclusive'},{title:'反馈精确率',dataIndex:'precision',render:(v:number,r)=>r.true_positive+r.false_positive===0?'样本不足':`${(v*100).toFixed(1)}%`}]}/></QueryState></Panel>
 <Panel title="评估数据集" actions={<Space><Input.Search aria-label="筛选规则" placeholder="规则 ID" onSearch={setRule}/><Select aria-label="反馈类型" value={type} onChange={setType} options={[{value:'',label:'全部判定'},...['true_positive','false_positive','false_negative','inconclusive'].map(v=>({value:v,label:v}))]}/></Space>}><QueryState query={q}><Table rowKey="feedback_id" dataSource={q.data?.rows} pagination={{pageSize:10}} columns={[
 {title:'判定',dataIndex:'feedback_type'},{title:'规则',dataIndex:'rule_id'},{title:'实体',dataIndex:'entity_id',render:(v:string)=>v?<Link to={`/entities/${encodeURIComponent(v)}`}>{v.slice(0,22)}…</Link>:'—'},{title:'依据',dataIndex:'reason',ellipsis:true},{title:'时间',dataIndex:'created_at',render:(v:string)=><TimeValue value={v}/>},{title:'',render:(_,r)=><Button type="link" onClick={()=>setSelected(r)}>证据上下文</Button>}
 ]}/></QueryState></Panel><Drawer title="反馈与证据关联" open={!!selected} onClose={()=>setSelected(undefined)} size={650}><Json value={selected}/></Drawer></div>;
}

function Secret({value,onClose,title}:{value:{secret:string;expires?:string};onClose:()=>void;title:string}){return <Modal open title={title} footer={<Button type="primary" onClick={onClose}>已安全保存，关闭</Button>} onCancel={onClose} destroyOnHidden><Alert type="warning" showIcon title="仅显示本次返回值" description="关闭后不保存到浏览器存储、查询缓存或日志。请存入授权的凭据管理系统。"/><Input.TextArea aria-label="一次性凭据" readOnly value={value.secret} rows={4}/>{value.expires&&<p>到期：{value.expires}</p>}</Modal>;}

function NewSource({onClose}:{onClose:()=>void}){
 const {token,can}=useAuth();const client=useQueryClient();const {message}=App.useApp();const [form]=Form.useForm();const [step,setStep]=useState(0);const request=useRef(new IdempotencyDraft());const [secret,setSecret]=useState<{secret:string}>();
 const releases=useQuery({queryKey:['releases'],enabled:can('release:read'),queryFn:({signal})=>api('/releases',token,undefined,releasesSchema,signal)});
 const mutation=useMutation({mutationFn:async()=>{const result=await api('/sources',token,{method:'POST',headers:{'Idempotency-Key':request.current.keyFor(JSON.stringify(form.getFieldsValue(true)))},body:JSON.stringify(form.getFieldsValue(true))},sourceSchema.extend({api_key:z.string()}));setSecret({secret:result.api_key});},onSuccess:()=>{void client.invalidateQueries({queryKey:['sources']});void message.success('来源已注册');},onError:e=>void message.error(messageOf(e))});
 return <><Modal open={!secret} title="新增数据来源" onCancel={()=>!mutation.isPending&&onClose()} footer={<Space>{step>0&&<Button disabled={mutation.isPending} onClick={()=>setStep(step-1)}>上一步</Button>}<Button type="primary" loading={mutation.isPending} onClick={()=>{if(step<2)void form.validateFields(step===0?['vendor_name','vendor_product','vendor_dataset']:['release_id','rate_limit']).then(()=>setStep(step+1)).catch(()=>{});else mutation.mutate();}}>{step===2?'确认注册':'下一步'}</Button></Space>}>
 <Steps size="small" current={step} items={[{title:'选择来源'},{title:'配置范围'},{title:'确认注册'}]}/><Form form={form} layout="vertical" initialValues={{rate_limit:1000}} className="wb-form">
 <div hidden={step!==0}><Form.Item name="vendor_name" label="厂商" rules={[{required:true,max:128}]}><Input/></Form.Item><Form.Item name="vendor_product" label="产品" rules={[{required:true,max:128}]}><Input/></Form.Item><Form.Item name="vendor_dataset" label="数据集" rules={[{required:true,max:128}]}><Input placeholder="如 Security / dns"/></Form.Item></div>
 <div hidden={step!==1}><QueryState query={releases}><Form.Item name="release_id" label="语义发布包" rules={[{required:true}]}>{can('release:read')?<Select options={releases.data?.items.filter(r=>['active','staged'].includes(r.state)).map(r=>({value:r.id,label:r.id+' / '+r.state}))}/>:<Input placeholder="输入已批准的 active / staged 发布引用"/>}</Form.Item></QueryState><Form.Item name="rate_limit" label="接入速率上限（EPS）" rules={[{required:true}]}><InputNumber min={1} max={100000}/></Form.Item></div>
 {step===2&&<><Descriptions column={1} items={Object.entries(form.getFieldsValue(true)).map(([k,v])=>({key:k,label:k,children:String(v)}))}/><Alert type="info" title="独立来源上下文与凭据" description="注册成功后凭据只返回一次。新来源不会自动安装组件或扩大已有采集范围。"/></>}
 </Form></Modal>{secret&&<Secret value={secret} title="来源注册成功" onClose={onClose}/>}</>;
}

export function SourcesWorkbench(){
 const {token,can}=useAuth();const [search,setSearch]=useState('');const [creating,setCreating]=useState(false);const [tab,setTab]=useState('sources');
 const q=useQuery({queryKey:['sources'],queryFn:({signal})=>api('/sources',token,undefined,sourcesSchema,signal),refetchInterval:30000});
 return <div className="page-stack"><PageHeader eyebrow="DATA SOURCES" title="数据来源" description="来源实例、采集状态和生效配置分开管理。" actions={can('source:manage')&&<Button type="primary" onClick={()=>setCreating(true)}>新增来源</Button>}/>
 <Tabs activeKey={tab} onChange={setTab} items={[{key:'sources',label:'来源实例'},{key:'agents',label:'Agent 与组件'},{key:'filters',label:'过滤策略'}]}/>
 {tab==='sources'?<Panel title="来源实例" actions={<Input.Search aria-label="搜索来源" value={search} onChange={e=>setSearch(e.target.value)} placeholder="名称、产品或 ID" allowClear/>}><QueryState query={q}><Table rowKey="id" pagination={{pageSize:10}} dataSource={q.data?.items.filter(r=>[r.vendor_product,r.vendor_dataset,r.id].join(' ').toLowerCase().includes(search.toLowerCase()))} columns={[
 {title:'名称 / 数据集',render:(_,r)=><Link to={`/sources/${encodeURIComponent(r.id)}`}>{r.vendor_name} · {r.vendor_product}<small className="wb-sub">{r.vendor_dataset}</small></Link>},{title:'许可',dataIndex:'enabled',render:(v:boolean)=><Tag color={v?'success':'default'}>{v?'有效':'停用'}</Tag>},{title:'状态',dataIndex:'state'},{title:'EPS 上限',dataIndex:'rate_limit'},{title:'语义发布',dataIndex:'release_id'},{title:'更新',dataIndex:'updated_at',render:(v:string)=><TimeValue value={v}/>}
 ]}/></QueryState></Panel>:tab==='agents'?<Agents embedded/>:<Panel title="版本化过滤策略"><Capability title="过滤策略管理尚未启用" description="当前 API 没有策略列表、影子匹配计数及启用/回滚接口。策略治理入口保留，不能假设保护场景或容量门禁已通过。"/><UnavailableAction reason="缺少过滤策略管理接口">新建 / 发布过滤策略</UnavailableAction></Panel>}
 {creating&&<NewSource onClose={()=>setCreating(false)}/>}</div>;
}

export function SourceDetail(){
 const {id=''}=useParams();const {token}=useAuth();const client=useQueryClient();const {message}=App.useApp();const [secret,setSecret]=useState<{secret:string}>();const [tab,setTab]=useState('status');
 const q=useQuery({queryKey:['sources'],queryFn:({signal})=>api('/sources',token,undefined,sourcesSchema,signal)});
 const collectors=useQuery({queryKey:['collectors'],queryFn:({signal})=>api('/collectors',token,undefined,collectorsSchema,signal)});
 const source=q.data?.items.find(r=>r.id===id);const bound=collectors.data?.items.flatMap(c=>(c.heartbeat?.sources??[]).filter(s=>s.source_id===id).map(s=>({...s,collector:c})))??[];
 const m=useMutation({mutationFn:async(action:'rotate'|'disable')=>{if(action==='rotate'){const r=await api(`/sources/${encodeURIComponent(id)}/rotate`,token,{method:'POST'},sourceSchema.extend({api_key:z.string()}));setSecret({secret:r.api_key});}else await api(`/sources/${encodeURIComponent(id)}`,token,{method:'DELETE'});},onSuccess:()=>{void client.invalidateQueries({queryKey:['sources']});void message.success('来源已更新');},onError:e=>void message.error(messageOf(e))});
 return <div className="page-stack"><Link to="/sources">← 数据来源</Link><PageHeader eyebrow="SOURCE WORKSPACE" title={source?`${source.vendor_product} · ${source.vendor_dataset}`:'来源详情'} description="来源许可、读取计数与语义配置。" actions={source?.enabled&&<Space><Popconfirm title="轮换此来源凭据？" description="旧凭据有 24 小时排空重叠期。" onConfirm={()=>m.mutate('rotate')}><Button loading={m.isPending}>轮换凭据</Button></Popconfirm><Popconfirm title="停用此来源？" description="撤销接入凭据；保留历史证据与配置。" onConfirm={()=>m.mutate('disable')}><Button danger loading={m.isPending}>停用来源</Button></Popconfirm></Space>}/>
 <QueryState query={q}>{!source?<EmptyState title="来源不存在" description="来源不在当前租户范围中。"/>:<><Tabs activeKey={tab} onChange={setTab} items={[{key:'status',label:'状态与计数'},{key:'config',label:'配置与发布'},{key:'gaps',label:'错误与缺口'}]}/>
 {tab==='status'?<Panel title="关联采集状态"><QueryState query={collectors}><Table rowKey={r=>r.collector.id} dataSource={bound} pagination={false} columns={[{title:'Agent',render:(_,r)=><Link to={`/agents/${encodeURIComponent(r.collector.id)}`}>{r.collector.hostname}</Link>},{title:'采集状态',dataIndex:'state'},{title:'读取',dataIndex:'events_read'},{title:'发送',dataIndex:'events_sent'},{title:'丢弃',dataIndex:'events_drop'},{title:'最近错误',dataIndex:'last_error'}]}/></QueryState><Capability title="确认链观测范围" description="心跳发送计数不等于 Raw receipt 或索引已确认。持久化水位和原始证据完整确认链尚无在线接口。"/></Panel>:tab==='config'?<Panel title="生效配置"><Descriptions column={1} items={sourceDescriptions(source)}/><Link to={`/releases/${encodeURIComponent(source.release_id)}`}>查看语义发布 →</Link><Capability title="配置变更" description="当前只支持注册、凭据轮换和停用；来源上下文切换及可恢复暂停尚缺少接口。"/></Panel>:<Panel title="来源诊断"><QueryState query={collectors}>{bound.filter(r=>r.last_error).map(r=><Alert key={r.collector.id} type="error" title={r.last_error}/>)}{!bound.some(r=>r.last_error)&&<EmptyState title="未报告来源错误" description="不代表已证明不存在读取缺口；完整缺口记录需独立接口。"/>}</QueryState><Link to="/audit">查看操作审计 →</Link></Panel>}</>}</QueryState>{secret&&<Secret title="新来源凭据" value={secret} onClose={()=>{setSecret(undefined);m.reset();}}/>}</div>;
}
function sourceDescriptions(s:SourceInstance){return [['来源 ID',s.id],['身份空间',s.namespace],['许可',s.enabled?'有效':'停用'],['状态',s.state],['Context',s.source_context_id],['Epoch',s.source_epoch],['发布',s.release_id],['EPS 上限',s.rate_limit]].map(([label,value])=>({key:String(label),label,children:String(value)}));}

export function Agents({embedded=false}:{embedded?:boolean}){
 const {token}=useAuth();const [secret,setSecret]=useState<{secret:string;expires:string}>();const [minutes,setMinutes]=useState(30);const [open,setOpen]=useState(false);const {message}=App.useApp();
 const q=useQuery({queryKey:['collectors'],queryFn:({signal})=>api('/collectors',token,undefined,collectorsSchema,signal),refetchInterval:30000});
 const enroll=useMutation({mutationFn:async()=>{const r=await api('/collectors/enrollments',token,{method:'POST',body:JSON.stringify({expires_in_minutes:minutes})},z.object({enrollment_token:z.string(),expires_at:z.string()}));setSecret({secret:r.enrollment_token,expires:r.expires_at});setOpen(false);},onError:e=>void message.error(messageOf(e))});
 return <div className="page-stack">{!embedded&&<PageHeader eyebrow="MANAGED AGENTS" title="Agent 与组件" description="管理连接与采集运行分别观测，离线保留最后有效配置。"/>}<Panel title="受管 Agent" actions={<Button type="primary" onClick={()=>setOpen(true)}>注册 Agent</Button>}><QueryState query={q}><Table rowKey="id" dataSource={q.data?.items} pagination={{pageSize:10}} columns={[
 {title:'主机',render:(_,r)=><Link to={`/agents/${encodeURIComponent(r.id)}`}>{r.hostname}<small className="wb-sub">{r.os} / {r.architecture}</small></Link>},{title:'管理',render:(_,r)=><Tag color={r.online?'success':'warning'}>{r.online?'在线':'离线'} / {r.state}</Tag>},{title:'采集',render:(_,r)=>r.heartbeat?.state??'尚无心跳'},{title:'Agent 版本',dataIndex:'installed_version'},{title:'期望 / 生效',render:(_,r)=>`v${r.desired_config_version} / v${r.config_version}`},{title:'队列',render:(_,r)=>r.heartbeat?.queue_depth??'未知'},{title:'心跳',dataIndex:'last_heartbeat_at',render:(v:string)=><TimeValue value={v}/>}
 ]}/></QueryState></Panel><Modal open={open} title="创建一次性 Agent 注册令牌" onCancel={()=>!enroll.isPending&&setOpen(false)} onOk={()=>enroll.mutate()} confirmLoading={enroll.isPending}><label>令牌有效期（分钟）</label><InputNumber aria-label="注册令牌有效期" min={5} max={1440} value={minutes} onChange={v=>setMinutes(v??30)}/><p>令牌供 Agent 注册使用，不是长期数据采集凭据。</p></Modal>{secret&&<Secret title="Agent 注册令牌" value={secret} onClose={()=>{setSecret(undefined);enroll.reset();}}/>}</div>;
}

export function AgentDetail(){
 const {id=''}=useParams();const {token}=useAuth();const client=useQueryClient();const {message}=App.useApp();const [operation,setOperation]=useState<'bind'|'upgrade'|undefined>();const [form]=Form.useForm();
 const q=useQuery({queryKey:['collectors'],queryFn:({signal})=>api('/collectors',token,undefined,collectorsSchema,signal),refetchInterval:30000});
 const sources=useQuery({queryKey:['sources'],queryFn:({signal})=>api('/sources',token,undefined,sourcesSchema,signal)});
 const agent=q.data?.items.find(x=>x.id===id);const [step,setStep]=useState(0);
 const m=useMutation({mutationFn:async({action,values}:{action:string;values?:Record<string,unknown>})=>{
  const base=`/collectors/${encodeURIComponent(id)}`;
  if(action==='disable')await api(base,token,{method:'DELETE'});else if(action==='enable')await api(base+'/enable',token,{method:'POST'});
  else if(action==='bind')await api(base+'/source-binding',token,{method:'PUT',body:JSON.stringify(values)});
  else {const config=componentConfiguration(String(values?.configuration),String(values?.component),String(values?.desired_version));await api(base+'/config',token,{method:'PUT',body:JSON.stringify(config)});}
 },onSuccess:()=>{void client.invalidateQueries({queryKey:['collectors']});setOperation(undefined);form.resetFields();void message.success('请求已接受；以 Agent 心跳确认实际生效状态。');},onError:e=>{void client.invalidateQueries({queryKey:['collectors']});void message.error(messageOf(e));}});
 function start(v:'bind'|'upgrade'){form.resetFields();setOperation(v);setStep(0);}
 return <div className="page-stack"><Link to="/agents">← Agent 与组件</Link><PageHeader eyebrow="AGENT WORKSPACE" title={agent?.hostname??'Agent 详情'} description="配置期望与实际生效对照，查看受管组件生命周期。" actions={agent&&<Space><Button onClick={()=>start('bind')}>绑定来源</Button><Button type="primary" onClick={()=>start('upgrade')}>组件升级 / 回滚</Button><Popconfirm title={agent.state==='disabled'?'恢复 Agent 准入？':'停用 Agent 并撤销绑定来源写入授权？'} description="部分授权操作失败会返回错误，需重试；不会显示全部成功。" onConfirm={()=>m.mutate({action:agent.state==='disabled'?'enable':'disable'})}><Button danger={agent.state!=='disabled'} loading={m.isPending}>{agent.state==='disabled'?'恢复准入':'停用 Agent'}</Button></Popconfirm></Space>}/>
 <QueryState query={q}>{!agent?<EmptyState title="Agent 不存在" description="不在当前租户范围中。"/>:<><Alert showIcon type={agent.online?'info':'warning'} title={agent.online?'管理面在线':'管理面离线'} description="管理在线与组件采集状态分别记录。以下为最近一次心跳报告。"/><div className="wb-two-column"><Panel title="配置与身份"><Descriptions column={1} items={agentDescriptions(agent)}/></Panel><Panel title="组件状态"><Table rowKey="component" dataSource={agent.heartbeat?.components??[]} pagination={false} columns={[{title:'组件',dataIndex:'component'},{title:'版本',dataIndex:'version'},{title:'状态',dataIndex:'state'},{title:'阶段',dataIndex:'phase'},{title:'重启',dataIndex:'restarts'}]}/></Panel></div><Panel title="诊断与来源"><p>{agent.heartbeat?.diagnostic||'未报告诊断'}</p><Table rowKey="source_id" dataSource={agent.heartbeat?.sources??[]} pagination={false} columns={[{title:'来源',dataIndex:'source_id',render:(v:string)=><Link to={`/sources/${encodeURIComponent(v)}`}>{v}</Link>},{title:'状态',dataIndex:'state'},{title:'读取',dataIndex:'events_read'},{title:'发送',dataIndex:'events_sent'},{title:'错误',dataIndex:'last_error'}]}/></Panel></>}</QueryState>
 <Modal title={operation==='bind'?'绑定数据来源':'受管组件升级 / 回滚'} open={!!operation} onCancel={()=>!m.isPending&&setOperation(undefined)} footer={<Space>{step>0&&<Button disabled={m.isPending} onClick={()=>setStep(step-1)}>上一步</Button>}<Button type="primary" loading={m.isPending} onClick={()=>{if(step<2)void form.validateFields().then(()=>setStep(step+1)).catch(()=>{});else m.mutate({action:operation!,values:form.getFieldsValue(true)});}}>{step===2?'确认提交':'下一步'}</Button></Space>}>
 <Steps size="small" current={step} items={[{title:'配置目标'},{title:'检查范围'},{title:'确认提交'}]}/><Form form={form} layout="vertical" className="wb-form"><div hidden={step!==0}>{operation==='bind'?<><QueryState query={sources}><Form.Item name="source_id" label="来源实例" rules={[{required:true}]}><Select options={sources.data?.items.filter(s=>s.enabled).map(s=>({value:s.id,label:s.vendor_product+' / '+s.vendor_dataset}))} onChange={v=>{const s=sources.data?.items.find(x=>x.id===v);form.setFieldValue('kafka_topic',s?`tuba.source.${s.source_context_id}.v1`:'');}}/></Form.Item></QueryState><Form.Item name="kafka_principal" label="已配置的 Kafka principal" rules={[{required:true,max:255}]}><Input/></Form.Item><Form.Item name="kafka_topic" label="来源精确 Topic" rules={[{required:true,pattern:/^tuba\.source\.ctx_[a-f0-9]{32}\.v[0-9]+$/}]}><Input/></Form.Item></>:<><Form.Item name="component" label="受管组件" rules={[{required:true}]}><Select options={agent?.heartbeat?.components?.map(c=>({value:c.component,label:c.component}))}/></Form.Item><Form.Item name="desired_version" label="目标版本（需已验签的本地制品）" rules={[{required:true,pattern:/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,63}$/}]}><Input maxLength={64}/></Form.Item><Form.Item name="configuration" label="当前完整配置（JSON）" rules={[{required:true},{validator:(_,value)=>{try{parseManagedConfiguration(String(value));return Promise.resolve();}catch{return Promise.reject(new Error('请输入完整 JSON 配置对象'));}}}]}><Input.TextArea rows={6} placeholder="从授权配置管理系统取得当前完整配置；不填明文凭据"/></Form.Item></>}</div>{step===1&&<Alert type="warning" showIcon title="生效前检查" description={operation==='bind'?'来源、主机和 principal 的租户及精确 Topic 由服务端核验。':'配置管理未提供读取端点。请核对提交的完整配置与最近发布版本一致；仅合并目标组件 desired_version，保留其他配置。Agent 验签、兼容检查和实际状态以心跳为准。'}/>} {step===2&&<Descriptions column={1} items={Object.entries(form.getFieldsValue(true)).map(([k,v])=>({key:k,label:k,children:String(v)}))}/>}</Form></Modal></div>;
}
function agentDescriptions(a:CollectorSummary){return [['Agent ID',a.id],['管理状态',a.online?'在线':'离线'],['采集状态',a.heartbeat?.state??'未知'],['期望 / 生效',`v${a.desired_config_version} / v${a.config_version}`],['版本',a.installed_version],['队列',a.heartbeat?.queue_depth??'未知']].map(([label,value])=>({key:String(label),label,children:String(value)}));}

export function ReleaseDetail(){
 const {id=''}=useParams();const {token,can}=useAuth();const client=useQueryClient();const {message}=App.useApp();const [confirm,setConfirm]=useState<string>();const [step,setStep]=useState(0);
 const q=useQuery({queryKey:['release',id],queryFn:({signal})=>api(`/releases/${encodeURIComponent(id)}`,token,undefined,releaseSchema,signal)});
 const audit=useQuery({queryKey:['release',id,'audit'],queryFn:({signal})=>api(`/releases/${encodeURIComponent(id)}/audit`,token,undefined,releaseAuditSchema,signal)});
 const m=useMutation({mutationFn:(action:string)=>api(`/releases/${encodeURIComponent(id)}/${action}`,token,{method:'POST'},releaseSchema),onSuccess:()=>{void client.invalidateQueries({queryKey:['release',id]});void client.invalidateQueries({queryKey:['releases']});setConfirm(undefined);void message.success('发布状态已更新');},onError:e=>void message.error(messageOf(e))});
 const next=q.data?.state==='draft'?'validate':q.data?.state==='validated'?'stage':q.data?.state==='staged'?'activate':undefined;const labels:Record<string,string>={validate:'校验',stage:'暂存',activate:'激活'};
 return <div className="page-stack"><Link to="/releases">← 语义发布</Link><PageHeader eyebrow="RELEASE WORKSPACE" title={id} description="资产、精确依赖、发布状态与审计。" actions={next&&can('release:manage')&&<Button type="primary" onClick={()=>{setConfirm(next);setStep(0);}}>{labels[next]}</Button>}/>
 <QueryState query={q}>{q.data&&<><Steps current={Math.max(0,['draft','validated','staged','active','retired'].indexOf(q.data.state))} items={['注册','校验','暂存','激活','退役'].map(title=>({title}))}/><Panel title="资产清单" actions={<Tag>{q.data.state} / {q.data.version}</Tag>}><Table rowKey="asset_id" dataSource={q.data.manifest.assets} pagination={false} columns={[{title:'资产',dataIndex:'asset_id'},{title:'类型',dataIndex:'kind'},{title:'版本',dataIndex:'version'},{title:'精确依赖',dataIndex:'dependencies',render:(v:string[])=>v.join(' / ')||'无'},{title:'SHA-256',dataIndex:'sha256',ellipsis:true}]}/></Panel><Panel title="兼容声明"><Descriptions column={1} items={Object.entries(q.data.manifest.compatibility).map(([k,v])=>({key:k,label:k,children:v}))}/></Panel></>}</QueryState>
 <Panel title="发布审计"><QueryState query={audit}><Table rowKey="id" dataSource={audit.data?.items} pagination={false} columns={[{title:'操作',dataIndex:'action'},{title:'操作者',dataIndex:'actor_subject'},{title:'时间',dataIndex:'occurred_at',render:(v:string)=><TimeValue value={v}/>},{title:'Request ID',dataIndex:'request_id'}]}/></QueryState></Panel><Capability title="生命周期边界" description="当前支持注册、校验、暂存和激活。独立退役、代次切换、资源预算查询与回滚管理接口尚未上线，不展示假定通过的门禁。"/>
 <Modal open={!!confirm} title={`${labels[confirm??'']??''}语义发布`} onCancel={()=>!m.isPending&&setConfirm(undefined)} footer={<Space>{step>0&&<Button disabled={m.isPending} onClick={()=>setStep(step-1)}>上一步</Button>}<Button type="primary" loading={m.isPending} onClick={()=>step<2?setStep(step+1):m.mutate(confirm!)}>{step===2?'确认提交':'下一步'}</Button></Space>}><Steps size="small" current={step} items={[{title:'候选版本'},{title:'生效边界'},{title:'确认提交'}]}/><div className="wb-form">{step===0?<Descriptions column={1} items={[{key:'id',label:'候选',children:id},{key:'state',label:'当前状态',children:q.data?.state},{key:'hash',label:'SHA-256',children:q.data?.sha256}]}/>:<Alert showIcon type="warning" title={step===1?'由服务端校验前置条件':'此操作将修改实际发布状态'} description="激活只允许当前阶段及独立发布授权；接口失败时保留候选版本，查看错误后重新核验。此流程不代表影子代次已完成对账。"/>}</div></Modal></div>;
}

export function Backups(){return <div className="page-stack"><PageHeader eyebrow="BACKUP & RECOVERY" title="备份与恢复" description="恢复范围、清单和异机目标的验证。" actions={<UnavailableAction reason="备份恢复控制接口尚未上线">恢复演练</UnavailableAction>}/><Capability title="备份状态尚无在线接口" description="无法确认最近成功时间、异机目标及实测 RPO/RTO，不显示原型中的演示指标。"/><div className="wb-two-column"><Panel title="恢复对象"><Descriptions column={1} items={[{key:'pg',label:'PG / 身份',children:'PG 备份与 WAL 恢复边界'},{key:'es',label:'ES',children:'Raw / UIM / 派生快照'},{key:'config',label:'发布与配置',children:'发布版本、配置哈希与审计水位'}]}/></Panel><Panel title="恢复验证顺序"><Steps direction="vertical" items={['核对异机备份与清单','恢复 PG 与身份','恢复发布 / 配置 / ES','核对 checkpoint 和可重读范围','实测恢复时长与数据损失'].map(title=>({title,status:'wait'}))}/></Panel></div></div>;}
export function Replay(){return <div className="page-stack"><PageHeader eyebrow="CONTROLLED REPLAY" title="回放与回填" description="固定输入范围，影子验证，对账后审批生产切换。" actions={<UnavailableAction reason="回放任务和切换接口尚未上线">新建回放</UnavailableAction>}/><Capability title="受控回放尚未提供在线接口" description="当前处理任务接口为 planned。创建、对账和切换暂不可用；不会写生产代次。"/><Panel title="生产切换检查"><Table rowKey="name" pagination={false} dataSource={['输入保留边界 / 固定尾水位','影子代次处理','输入 = 成功 + 隔离','outbox / 下游 lag','索引新鲜度','风险代次唯一','回滚资源与期限'].map(name=>({name,state:'未取得验证结果'}))} columns={[{title:'检查项',dataIndex:'name'},{title:'当前结果',dataIndex:'state'}]}/></Panel><Link to="/jobs">查看任务中心 →</Link></div>;}
export function JobDetail(){return <div className="page-stack"><Link to="/jobs">← 任务中心</Link><PageHeader eyebrow="JOB WORKSPACE" title="处理任务详情" description="输入快照、执行尝试与安全取消边界。"/><Capability title="处理任务详情尚不可用" description="当前后端未实现 /jobs/{id}，无法读取 attempt、lease、checkpoint 或提交取消。导出任务请在任务中心查看实际回执。"/></div>;}

function RegisterRelease({onClose}:{onClose:()=>void}){
 const {token}=useAuth();const client=useQueryClient();const {message}=App.useApp();const navigate=useNavigate();const [form]=Form.useForm();const [step,setStep]=useState(0);const request=useRef(new IdempotencyDraft());
 const m=useMutation({mutationFn:()=>api('/releases',token,{method:'POST',headers:{'Idempotency-Key':request.current.keyFor(String(form.getFieldValue('manifest')))},body:form.getFieldValue('manifest') as string},releaseSchema),onSuccess:r=>{void client.invalidateQueries({queryKey:['releases']});void message.success('发布包已注册');onClose();navigate('/releases/'+encodeURIComponent(r.id));},onError:e=>void message.error(messageOf(e))});
 return <Modal open title="注册语义发布包" onCancel={()=>!m.isPending&&onClose()} footer={<Space>{step>0&&<Button disabled={m.isPending} onClick={()=>setStep(step-1)}>上一步</Button>}<Button type="primary" loading={m.isPending} onClick={()=>step<2?void form.validateFields().then(()=>setStep(step+1)).catch(()=>{}):m.mutate()}>{step===2?'确认注册':'下一步'}</Button></Space>}><Steps size="small" current={step} items={[{title:'提交清单'},{title:'资产与依赖'},{title:'确认注册'}]}/><Form form={form} layout="vertical" className="wb-form"><div hidden={step!==0}><Form.Item name="manifest" label="完整 Manifest JSON" rules={[{required:true},{validator:(_,v)=>{try{const x=JSON.parse(String(v));if(!x.release_id||!x.version||!Array.isArray(x.assets))throw new Error();return Promise.resolve();}catch{return Promise.reject(new Error('清单需包含 release_id、version 和 assets'));}}}]}><Input.TextArea rows={12} placeholder="粘贴已准备的不可变发布清单"/></Form.Item></div>{step===1&&<Json value={JSON.parse(String(form.getFieldValue('manifest')))}/>} {step===2&&<Alert showIcon type="info" title="注册为 draft" description="此操作仅注册清单，不上传制品，不激活生产。后续在详情页逐阶段校验、暂存和激活。"/>}</Form></Modal>;
}
export function ReleaseList(){
 const {token,can}=useAuth();const [open,setOpen]=useState(false);const [filter,setFilter]=useState('');
 const q=useQuery({queryKey:['releases'],queryFn:({signal})=>api('/releases',token,undefined,releasesSchema,signal)});
 return <div className="page-stack"><PageHeader eyebrow="SEMANTIC RELEASES" title="语义发布" description="解析、质量、归因与分析资产的一致版本快照。" actions={can('release:manage')&&<Button type="primary" onClick={()=>setOpen(true)}>注册发布包</Button>}/><Panel title="发布包版本" actions={<Input.Search aria-label="搜索发布包" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="名称或版本" allowClear/>}><QueryState query={q}><Table rowKey="id" dataSource={q.data?.items.filter(x=>(x.id+' '+x.version).includes(filter))} pagination={{pageSize:10}} columns={[{title:'发布包',dataIndex:'id',render:(v:string)=><Link to={`/releases/${encodeURIComponent(v)}`}>{v}</Link>},{title:'版本',dataIndex:'version'},{title:'状态',dataIndex:'state',render:(v:string)=><Tag color={v==='active'?'success':v==='staged'?'processing':'default'}>{v}</Tag>},{title:'资产',render:(_,r)=>r.manifest.assets.length},{title:'创建',dataIndex:'created_at',render:(v:string)=><TimeValue value={v}/>},{title:'激活',dataIndex:'activated_at',render:(v:string)=><TimeValue value={v}/>}]}/></QueryState></Panel><Alert type="info" title="独立发布授权" description="发布状态推进由服务端验证，租户管理员身份不自动取得平台发布授权。"/>{can('release:manage')&&<Link to="/publishers">管理独立发布授权 →</Link>}{open&&<RegisterRelease onClose={()=>setOpen(false)}/>}</div>;
}
export function PublisherPanel(){
 const {token,can}=useAuth();const {message}=App.useApp();const [form]=Form.useForm();const [values,setValues]=useState<{subject:string;action:string}>();
 const m=useMutation({mutationFn:()=>api(`/platform/release-publishers/${encodeURIComponent(values!.subject)}`,token,{method:values!.action==='grant'?'PUT':'DELETE'}),onSuccess:()=>{setValues(undefined);form.resetFields();void message.success('独立发布授权已更新');},onError:e=>void message.error(messageOf(e))});
 if(!can('release:manage'))return null;
 return <Panel title="独立发布者授权"><Alert showIcon type="info" title="平台授权单独管理" description="当前没有发布者查询接口。只对明确的 IAM subject 提交授权变更，操作结果以服务端验证为准。"/><Form form={form} layout="vertical" className="wb-panel-body" onFinish={setValues}><Form.Item name="subject" label="IAM subject" rules={[{required:true,max:256}]}><Input/></Form.Item><Form.Item name="action" label="操作" rules={[{required:true}]}><Select options={[{value:'grant',label:'授予发布授权'},{value:'revoke',label:'撤销发布授权'}]}/></Form.Item><Button htmlType="submit">复核变更</Button></Form><Modal open={!!values} title="确认独立发布授权变更" onCancel={()=>!m.isPending&&setValues(undefined)} onOk={()=>m.mutate()} confirmLoading={m.isPending}><Descriptions column={1} items={[{key:'subject',label:'对象',children:values?.subject},{key:'action',label:'操作',children:values?.action==='grant'?'授予':'撤销'}]}/></Modal></Panel>;
}
export function Publishers(){return <div className="page-stack"><Link to="/releases">← 语义发布</Link><PageHeader eyebrow="PUBLISH AUTHORIZATION" title="独立发布授权" description="平台发布授权与租户成员角色分别管理。"/><PublisherPanel/></div>;}

export function ExportDetail(){
 const {id=''}=useParams();const {token}=useAuth();const client=useQueryClient();const {message}=App.useApp();
 const q=useQuery({queryKey:['export',id],queryFn:({signal})=>api(`/exports/${encodeURIComponent(id)}`,token,undefined,exportJobSchema,signal),refetchInterval:query=>['queued','running'].includes(query.state.data?.state??'')?5000:false});
 const m=useMutation({mutationFn:async()=>{
  const response=await fetch(`/api/v1/exports/${encodeURIComponent(id)}/download`,{headers:token?{Authorization:`Bearer ${token}`}:{}});
  if(response.status===401)window.dispatchEvent(new Event('tuba:unauthorized'));
  if(!response.ok)throw new APIError(response.status,(await response.text())||'导出下载失败');
  const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`tuba-export-${id}.${q.data?.format==='csv'?'csv':'ndjson'}`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 },onSuccess:()=>{void client.invalidateQueries({queryKey:['export',id]});void client.invalidateQueries({queryKey:['exports']});void message.success('导出文件已下载');},onError:e=>void message.error(messageOf(e))});
 const expired=!!q.data?.expires_at&&new Date(q.data.expires_at).getTime()<=Date.now();
 return <div className="page-stack"><Link to="/jobs">← 任务中心</Link><PageHeader eyebrow="QUERY EXPORT" title="导出任务详情" description="固定查询快照、限制与下载授权。" actions={<Popconfirm title="下载此导出文件？" description="下载时重新授权；链接仅可使用一次。" onConfirm={()=>m.mutate()}><Button type="primary" loading={m.isPending} disabled={!q.data||q.data.state!=='succeeded'||!!q.data.downloaded_at||expired||m.isSuccess}>下载结果</Button></Popconfirm>}/><QueryState query={q}>{q.data&&<><Panel title="任务回执"><Descriptions column={1} items={[
 {key:'id',label:'任务',children:q.data.id},{key:'state',label:'状态',children:<Tag>{q.data.state}</Tag>},{key:'scope',label:'数据集',children:q.data.dataset},{key:'query',label:'查询快照',children:<code>{q.data.query}</code>},
 {key:'range',label:'时间范围',children:`${q.data.from} → ${q.data.to}`},{key:'format',label:'格式',children:q.data.format},{key:'count',label:'行数 / 字节',children:`${q.data.row_count??'—'} / ${q.data.byte_count??'—'}`},{key:'limit',label:'上限',children:`${q.data.row_limit} 行 / ${q.data.byte_limit} 字节`},{key:'stop',label:'截断原因',children:q.data.limit_reached||'无'},
 {key:'hash',label:'文件 SHA-256',children:q.data.file_sha256||'尚未生成'},{key:'expires',label:'下载到期',children:q.data.expires_at??'未知'},{key:'downloaded',label:'下载状态',children:q.data.downloaded_at?'已使用':expired?'已过期':'尚未使用'}]}/></Panel>{q.data.error&&<Alert showIcon type="error" title={q.data.error}/>}<Alert type="info" title="下载授权边界" description="文件内容按创建时权限快照控制；下载时服务端重新校验成员权限，过期或已使用的结果不可再次下载。"/></>}</QueryState></div>;
}
